import type { Metadata } from "next";

import ReactQueryProvider from "@/_components/ReactQueryProvider";

import "./globals.css";
import NavWrapper from "@/_components/Navigation/NavWrapper";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="overflow-hidden"
      >
        <ReactQueryProvider>
          <NavWrapper>
            {children}
          </NavWrapper>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
