import type { Metadata } from "next";

import ReactQueryProvider from "@/_components/ReactQueryProvider";

// 1. import `HeroUIProvider` component
import { HeroUIProvider } from "@heroui/react";

import "./globals.css";
import NavWrapper from "@/_components/Navigation/NavWrapper";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="overflow-hidden"
      >
        <ReactQueryProvider>
          <HeroUIProvider>
            <NavWrapper>
              {children}
            </NavWrapper>
          </HeroUIProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
