import type { Metadata } from "next";

import ReactQueryProvider from "@/_components/ReactQueryProvider";

// 1. import `HeroUIProvider` component
import { HeroUIProvider } from "@heroui/react";

import "@styles/globals.css";

import "mapbox-gl/dist/mapbox-gl.css";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className="overflow-hidden"
            >
                <ReactQueryProvider>
                    <HeroUIProvider>
                        {children}
                    </HeroUIProvider>
                </ReactQueryProvider>
            </body>
        </html>
    );
}